# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch

import torch

# Create random tensor
tensor = torch.rand(7,7)
tensor,tensor.device


(tensor([[0.8683, 0.7526, 0.2293, 0.3552, 0.3049, 0.6769, 0.9200],
         [0.8793, 0.2773, 0.8123, 0.9824, 0.0912, 0.6773, 0.4874],
         [0.1301, 0.0421, 0.4062, 0.6866, 0.7533, 0.3474, 0.4984],
         [0.0673, 0.6136, 0.0441, 0.0692, 0.9013, 0.1826, 0.1714],
         [0.5718, 0.3928, 0.3966, 0.6032, 0.4466, 0.1677, 0.7266],
         [0.0567, 0.5740, 0.3042, 0.8773, 0.6213, 0.6059, 0.9445],
         [0.8712, 0.1372, 0.0547, 0.3314, 0.1170, 0.7748, 0.2100]]),
 device(type='cpu'))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor
another_tensor = torch.rand(1,7)

# Perform matrix multiplication
torch.matmul(tensor , another_tensor.T)

tensor([[1.4238],
        [1.3883],
        [1.1636],
        [1.1734],
        [1.2370],
        [1.4814],
        [0.6966]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [17]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

# Create two random tensors
rand1 = torch.rand(7,7)
# torch.manual_seed(RANDOM_SEED)
rand2 = torch.rand(7,1)

# Matrix multiply tensors
r3 = torch.mm(rand1 ,rand2)
print(r3)
r3.shape


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


torch.Size([7, 1])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [18]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [28]:
# Set random seed
RANDOM_SEED = torch.cuda.manual_seed(1234)

# Check for access to GPU
torch.cuda.is_available()
# Create two random tensors on GPU
device = 'cuda' if torch.cuda.is_available() else "cpu"

# x = torch.rand([3,4],device = 'cuda')
# y = torch.rand([3,4],device = 'cuda')
x = torch.rand(2,4).to(device)
y= torch.rand(2,4).to(device)
x ,y

(tensor([[0.2952, 0.7967, 0.1957, 0.9537],
         [0.8426, 0.0784, 0.3756, 0.5226]], device='cuda:0'),
 tensor([[0.5730, 0.6186, 0.6962, 0.5300],
         [0.2560, 0.7366, 0.0204, 0.2036]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [32]:
# Perform matmul on tensor_A and tensor_B
output = torch.matmul(x , y.T)
output, torch.matmul(x , y.T).shape


(tensor([[1.3037, 0.8606],
         [1.0697, 0.3875]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [36]:
# Find max
print(output.max())
# Find min
output.min()

tensor(1.3037, device='cuda:0')


tensor(0.3875, device='cuda:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [38]:
# Find arg max
output.argmax() ,output.argmin()

# Find arg min


(tensor(0, device='cuda:0'), tensor(3, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [41]:
# Set seed
RANDOM_SEED = 7

# Create random tensor
a = torch.rand(1,1,1,10)


# Remove single dimensions
aremoved1 = torch.squeeze(a)

# Print out tensors and their shapes
print(a ,a.shape)
print(aremoved1 , aremoved1.shape)



tensor([[[[0.8405, 0.4968, 0.2515, 0.1168, 0.0321, 0.0780, 0.3986, 0.7742,
           0.7703, 0.0178]]]]) torch.Size([1, 1, 1, 10])
tensor([0.8405, 0.4968, 0.2515, 0.1168, 0.0321, 0.0780, 0.3986, 0.7742, 0.7703,
        0.0178]) torch.Size([10])
